{% set name = "river-py" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pbotros/river/archive/refs/tags/v1.0.3.tar.gz
  sha256: e931af61f16433275f9bd6f2c27137af49c61557a510c79490e9e809544bd94c 

build:
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [not win]
    - ninja  # [win]
    - pkg-config
  host:
    - river-cpp {{ version }}
    - python
    - cython
    - setuptools
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - river

about:
  home: https://github.com/pbotros/river
  summary: 'High-throughput, structured, and persistent streaming'
  description: |
    A high-throughput, structured streaming framework built atop Redis Streams, with optional support for persistence-to-disk. C++ and Python support.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pbotros
