{% set name = "river-py" %}
{% set version = "1.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pbotros/river/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 8e730d12c59a187dc687ab8959e113494a0ef73a8d42315d93234d3b637c78fb

build:
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [not win]
    - ninja  # [win]
    - pkg-config
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - river-cpp {{ version }}
    - python
    - cython
    - setuptools
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - river

about:
  home: https://github.com/pbotros/river
  summary: High-throughput, structured, and persistent streaming
  description: |
    A high-throughput, structured streaming framework built atop Redis Streams, with optional support for persistence-to-disk. C++ and Python support.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pbotros
