{% set name = "river-py" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pbotros/river/archive/refs/tags/v1.0.1.tar.gz
  sha256: bf56544197697eefaa331daa793c1c9e0f643012860c5fbcba055557e5fca84a

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [not win]
    - ninja  # [win]
    - pkg-config
  host:
    - river-cpp {{ version }}
    - python
    - glog
    - cython
    - setuptools
    - pip
  run:
    - python

test:
  imports:
    - river

about:
  home: https://github.com/pbotros/river
  summary: 'High-throughput, structured, and persistent streaming'
  description: |
    A high-throughput, structured streaming framework built atop Redis Streams, with optional support for persistence-to-disk. C++ and Python support.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pbotros
